### ISSUE TITLE
Add Corner cross to settings modal

### ISSUE THREAD

**Issue by krestenlaust** [cs-24-sw-2-14/MagicBoard#76]
Simulation:
![Image](https://github.com/cs-24-sw-2-14/MagicBoard/assets/17174333/1813feec-ff5a-4447-a1d6-4c64f13a8247)

**Comment by JakobTopholt** [comment]
Depending on the implementation of the modal making the cross do the equivalent of pressing "Esc" could be an easy solution, remember to give the button a bit of padding

**Comment by krestenlaust** [comment]
> Depending on the implementation of the modal making the cross do the equivalent of pressing "Esc" could be an easy solution, remember to give the button a bit of padding

Oh that's a good idea! And thanks for the pointer about padding!
